### ISSUE TITLE
Your URL on Puppet Forge is Incorrect

### ISSUE THREAD

**Issue by woodsbw** [mklauber/puppet-aide#5]
It points to https://github.com/mklauber/aide, not https://github.com/mklauber/puppet-aide

**Comment by walidshaari** [comment]
Same issue in here. your URL is still not up2date.

**Comment by kevinduterne** [comment]
Closer but still incorrect https://github.com/mklauber/puppet-aidee instead of https://github.com/mklauber/puppet-aide
