### ISSUE TITLE
Update readme to clarify that this project is not actively maintained

### ISSUE THREAD

**Issue by lukehinds** [mklauber/puppet-aide#8]
Hello, I noted issue in issue #4 you mentioned that you no longer use puppet. If that is the case, will this be maintained still?

**Comment by mklauber** [comment]
Not to any significant degree.  I will accept bug fixes and keep the repo here for anyone who needs it, but I'm actively avoiding adding features in case things break. Feel free to fork and maintain it though.  I'll update the readme to make sure that's clear.

**Comment by lukehinds** [comment]
thanks @mklauber - I might write something from new (mainly as learning experience), but I will definitely add credit when your approach influences.
